version: "3.9"

services:
  api:
    restart: always
    hostname: api
    build: .
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - "./app:/app/app"
    command: /start-reload.sh
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  admin:
    image: adminer
    restart: always
    ports:
      - 5001:8080
    depends_on:
      - db

volumes:
  db-data:
